### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ibrokemycomputer** [SeanJM/atom-css-clean#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: "Arch Linux"
**Thrown From**: [atom-css-clean](https://github.com/SeanJM/atom-css-clean) package 2.19.6

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/nerd/.atom/packages/atom-css-clean/node_modules/css-clean/src/vendor/splitByComma.js:5

TypeError: Cannot read property 'length' of undefined
    at splitByComma (/packages/atom-css-clean/node_modules/css-clean/src/vendor/splitByComma.js:5:16)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/propertyGroup/background.js:20:21
    at Array.map (native)
    at formatLinearGradient (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/propertyGroup/background.js:17:8)
    at Object.module.exports (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/propertyGroup/background.js:38:12)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/propertyGroup.js:9:32)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:26:30
    at Array.map (native)
    at mapValue (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:25:17)
    at nested (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/nested.js:29:10)
    at Object.selector (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/selector.js:5:11)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:26:30
    at Array.map (native)
    at mapValue (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:25:17)
    at getValue (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/getValue.js:4:10)
    at cleanCss (/packages/atom-css-clean/node_modules/css-clean/index.js:19:10)
    at module.exports (/packages/atom-css-clean/node_modules/css-clean/index.js:23:10)
    at /packages/atom-css-clean/main.js:43:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -1:22 command-palette:toggle (input.hidden-input)
     -1:17.8.0 settings-view:install-packages-and-themes (input.hidden-input)
     -1:13.5.0 core:confirm (input.hidden-input)
     -0:15.7.0 css-clean:convert (input.hidden-input)
     -0:08.8.0 core:select-all (input.hidden-input)
     -0:02.6.0 css-clean:convert (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
atom-beautify 0.29.17 
atom-css-clean 2.19.6 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 1.3.9 
atom-typescript 10.1.14 
emmet 2.4.3 
language-vue 0.21.2 
seti-syntax 1.1.2 
seti-ui 1.6.1 
webbox-color 0.5.9 
```

**Comment by SeanJM** [comment]
Can you include the CSS which caused the issue?

**Comment by ibrokemycomputer** [comment]
```
@import url('https://fonts.googleapis.com/css?family=Noto+Sans|Roboto+Condensed');

/* BOX SIZING FIXES
---------------------------------------------------------------------------- */
*,
*:before,
*:after {
  box-sizing: border-box;
}

/* VARIABLES
---------------------------------------------------------------------------- */
:root {
  /* COLORS */
  --blue--light:        rgba(42, 143, 208, 1);
  --blue--translucent:  rgba(0, 129, 198, 0.8);
  --blue:               rgba(0, 129, 198, 1);
  --grey--text:         rgba(124, 123, 127, 1);
  --grey--light:        rgba(226, 226, 227, 1);
  --grey:               rgba(112, 111, 115, 1);
  --red--dark:          rgba(235, 65, 72, 1);
  --red:                rgba(237, 64, 72, 1);

  /* FONTS */
  --font-family:        'Noto Sans', sans-serif;
  --font-family--alt:   'Roboto Condensed', sans-serif;
}

/* DEFAULTS
---------------------------------------------------------------------------- */
html {
  font-size: 10px;
}
body {
  -webkit-font-smoothing: antialiased;
  color: var(--grey--text);
  font-family: var(--font-family);
  font-size: 1.4rem;
  line-height: 2.1rem;
  margin: 0;
  overflow-x: hidden;
}

/* HEADLINES
---------------------------------------------------------------------------- */
h1,
.h1,
h2,
.h2 {
  color: var(--red);
}

h1,
.h1 {
  font-family: var(--font-family--alt);
  font-size: 2.8rem;
  font-weight: bold;
  line-height: 1;
  margin: 0 0 2.8rem;
  text-transform: uppercase;
}

h2,
.h2 {
  font-family: var(--font-family);
  font-size: 2.1rem;
  font-weight: normal;
  line-height: 1.33333333;
  margin: 2.8rem 0 2.1rem;
}

h3,
.h3 {
  color: var(--grey);
  font-size: 2.8rem;
  font-weight: bold;
  margin: 0 0.7rem;
}

/* COPY
---------------------------------------------------------------------------- */
p,
ul {
  margin: 2.1rem 0;
}

.strong {
  font-weight: bold;
}

.rounded {
  border-radius: 0.7rem;
}


/* LISTS
---------------------------------------------------------------------------- */
ul {
  list-style-type: none;
  padding: 0 0 0 0.5rem;
}
li {
  margin: 1.4rem 0;
  padding: 0 0 0 1.6rem;
  position: relative;
}
ul li:before {
  content: '\2022';
  left: 0;
  position: absolute;
}

.flat-list li:before {
  content: '';
}

.flat-list--first {
  color: white;
  font-weight: bold;
}

/* BACKGROUNDS
---------------------------------------------------------------------------- */
.bg {
  background-color: white;
  width: 100%;
}
.bg--primary {
  background-color: var(--blue);
}
.bg--primary-translucent {
  background-color: var(--blue--translucent);
}
.bg--grey {
  background-color: var(--grey);
  color: white;
}

.bg--grey--light {
  background-color: var(--grey--light);
}

.bg--black {
  background-color: black;
}

/* INNER CONTENT
---------------------------------------------------------------------------- */
.inner {
  margin: 0 auto;
  max-width: 960px;
  padding: 10rem 0;
  position: relative;
  width: 100%;
}

.inner--short,
.inner--header {
  padding: 2.8rem 0;
}

.inner--secondary {
  padding: 3rem 0;
}

.inner--staggered {
  padding: 10rem 0 5rem;
}

.inner--tiny {
  padding: 2.1rem 0;
}

.inner--slider {
  padding: 2.1rem 0 0;
}

.inner--bottom {
  padding: 0 0 2.1rem;
}

.inner--footer {
  padding: 2.6rem 0;
}

.inner--med {
  padding: 9.6rem 0 7.6rem;
}

.inner--main {
  padding: 10rem 0 1.4rem;
}

.inner--flat {
  padding: 0;
}

/* BANNER
---------------------------------------------------------------------------- */
.banner {
  background: black;
  color: white;
  height: 440px;
  position: relative;
}

.banner--home {
  background: black;
  color: white;
  height: 600px;
  position: relative;
}

.banner__background {
  background-image: url('/img/banner__1.jpg');
  background-position: 50% 50%;
  height: 100%;
  opacity: 0.5;
  pointer-events: none;
  position: absolute;
  top: 0;
  width: 100%;
  z-index: 1;
}

.banner__row {
    align-items: flex-end;
    display: flex;
    justify-content: space-between;
    margin: 0.7rem 0 3rem;
    position: relative;
    z-index: 5;
}

.banner__left {
  align-items: baseline;
  display: flex;
  flex-flow: row wrap;
  justify-content: flex-start;
  max-width: 260px;
}

.selection__upper {
  color: rgba(255, 255, 255, 0.6);
  flex: 2;
  font-family: var(--font-family--alt);
  font-size: 1.3rem;
  font-weight: bold;
  min-width: 220px;
  text-transform: uppercase;
}

.selection__lower {
  font-size: 3.5rem;
  margin: 1.4rem 1.4rem 0 0;
}

.selection__drop {
  font-style: italic;
  text-transform: lowercase;
}

.selection__drop:after {
  border-left: 0.5rem solid transparent;
  border-right: 0.5rem solid transparent;
  border-top: 0.5rem solid white;
  content: '';
  left: 0.7rem;
  position: relative;
  top: 1.4rem;
}


.banner__right {
  align-items: baseline;
  display: flex;
  flex-flow: row wrap;
  justify-content: flex-end;
}

.banner__right span {
  color: rgba(255, 255, 255, 0.6);
  font-size: 2.1rem;
  margin: 0 0.35rem;
}


.banner__right .banner__right--item2 {
    color: rgba(255, 255, 255, 1);
    font-weight: bold;
}

.banner__right .banner__right--item2,
.banner__right .banner__right--item4 {
  margin-right: 3rem;
}

.banner__right .banner__right--item4 {
  font-size: 1.4rem;
}

.banner__slider {
    align-items: center;
    display: flex;
    position: relative;
    top: 5.7rem;
    z-index: 10;
}

.banner__slider-bg {
    position: absolute;
}

.banner__slider--controls {
  display: flex;
  justify-content: center;
  position: relative;
  top: 11rem;
}

.banner__slider--control {
  background-color: rgba(255, 255, 255, 0.6);
  border-radius: 1.4rem;
  display: inline-block;
  height: 1.4rem;
  margin: 1.4rem 0.5rem;
  overflow: hidden;
  width: 1.4rem;
  z-index: 999;
}

.banner__slider--control--active {
  background-color: rgba(0, 0, 0, 0.6);
  border-radius: 1.4rem;
  display: inline-block;
  height: 1.4rem;
  margin: 1.4rem 0.5rem 0;
  overflow: hidden;
  width: 1.4rem;
  z-index: 999;
}


.banner__slider-content {
  display: flex;
  height: 100%;
  justify-content: space-between;
  padding: 0 4.8rem;
  position: inherit;
  width: 100%;
}

.banner__slider-text-wrapper {
  display: flex;
  flex-flow: column nowrap;
  justify-content: flex-start;
  position: relative;
}


.banner__slider-text-main {
  font-size: 2.1rem;
  font-style: italic;
  margin-bottom: 1.4rem;
}

.banner__slider-text-sub {
  font-size: 2.8rem;
  font-style: italic;
  font-weight: bold;
}

.banner__slider-close {
    font-size: 1.8rem;
    position: absolute;
    right: 11px;
    top: -42px;
}

.secondary-nav {
  position: absolute;
  transform: translateY(-100%);
  z-index: 2;
}

/* HEADER
---------------------------------------------------------------------------- */
.header {
  left: 0;
  top: 0;
  width: 100%;
  z-index: 500;
}

.header--language {
  color: white;
  display: block;
  font-size: 1.2rem;
  padding: 0.7rem 0;
}

.header__logo {
  height: 52px;
  width: 176px;
}

.header__nav {
  position: absolute;
  right: 0;
  top: 68px;
}

.header__nav--link {
  color: var(--grey--text);
  font-style: italic;
  letter-spacing: -0.7px;
  line-height: 1;
  margin: 0 2rem;
  text-decoration: none;
}

.header__nav--link:last-child {
  margin-right: 0;
}

.search svg {
  fill: var(--grey--text);
  height: 1.6rem;
  transform: translateY(0.1rem);
  width: 1.6rem;
}

.active {
  color: var(--red);
}

.nav__secondary--link {
  color: white;
  font-size: 1.8rem;
  font-weight: normal;
  line-height: 1;
  padding: 0 4rem;
  position: relative;
  text-decoration: none;
  text-transform: capitalize;
}


.white-up-triangle-active:after {
  border-bottom: 1rem solid white;
  border-left: 1rem solid transparent;
  border-right: 1rem solid transparent;
  content: '';
  height: 0;
  position: absolute;
  right: 45%;
  right: calc(50% - 1rem);
  top: 44px;
  width: 0;
}

.nav__secondary--link:not(:first-child) {
  border-left: 1px solid rgba(255,255,255,0.2);
}


/* ROWS AND COLUMNS
---------------------------------------------------------------------------- */
.row {
  display: flex;
  width: 100%;
}

.row--centered {
  justify-content: center;
}

.row--base {
  align-items: baseline;
}

.row--cards {
  flex-flow: row wrap;
  justify-content: space-between;
}

.row--reverse {
  justify-content: flex-end;
}

.row--detail {
  align-items: center;
  border-bottom: rgba(112, 111, 115, 0.2) solid 1px;
  border-top: rgba(112, 111, 115, 0.2) solid 1px;
  justify-content: flex-start;
  margin: -1rem 0 8rem;
  padding: 4.8rem 0;
}

.flex-grow {
  flex-grow: 1;
}

/*.col {
  width: 100%;
  margin: 0 2.1rem;
}*/

.col-1 {
  flex: 1;
  height: 0%;
  margin: 0 1rem;
  padding: 0 2.1rem;
}

.col-2 {
  flex: 2;
}

.col-1-2 {
  width: calc(50% - 1.4rem);
}

.col-1-2:nth-child(odd) {
  margin-left: 0;
}

.col-1-2:nth-child(even) {
  margin-right: 0;
}

/* INPUTS AND FORMS
---------------------------------------------------------------------------- */
.button {
  border-radius: 7px;
  border: none;
  color: white;
  font-weight: bold;
  padding: 1.6rem 4.4rem;
  text-decoration: none;
  text-transform: uppercase;
  z-index: 999;
}

.input--text {
  border-radius: 7px;
  border: #b8b8ba 1px solid;
  padding: 1.5rem;
}

.subscribe-form {
  position: relative;
  width: 100%;
}

.subscribe-form__label {
  display: block;
  font-weight: bold;
  margin: 0;
  padding: 0 0 1.4rem;
  text-transform: uppercase;
}

.subscribe-form__input {
  width: calc(100% - 4.4rem);
}

.subscribe-form__submit {
  position: absolute;
  right: 0;
}



/* FOOTER
---------------------------------------------------------------------------- */
.footer__social {
  background: rgba(0,0,0,0.1);
  padding: 10rem 0 5rem 0;
}

.footer__social--inner {
  display: flex;
  flex-flow: row nowrap;
  justify-content: flex-end;
  align-items: center;
}

.footer__share {
  margin-right: auto;
}

.footer__share--label {
  display: block;
  font-weight: bold;
  padding: 0 0 2.1rem;
  text-transform: uppercase;
}

.footer__share--icon {
  background: rgba(255,255,255,0.2);
  border-radius: 40px;
  margin-right: 1rem;
  padding: 1.4rem 2.1rem 1.4rem;
}

.footer-subscribe {
  max-width: 450px;
}

.footer__main li {
  line-height: 1.9rem;
  margin: 1.4rem 0;
}

.footer__navigation--right {
  color: #e7e7e7;
  display: flex;
  flex-flow: row nowrap;
  padding-left: 80px;
}
.footer__navigation--right:after {
  background: rgba(255, 255, 255, 0.2);
  content: '';
  height: 100%;
  left: 185px;
  position: absolute;
  top: 0;
  width: 99999999px;
}

.footer__contact {
  padding-left: 2.1rem;
}

.footer__contact--link {
  color: white;
  padding-left: 1rem;
  text-decoration: none;
}

.contact-strong {
  color: white;
}

.footer__footer {
  background: rgba(0,0,0,0.1);
  font-size: 1.3rem;
  padding: 4.1rem 0;
}

.footer__footer--link {
  border-right: rgba(255,255,255,0.2) solid 1px;
  color: white;
  padding: 0 1rem;
  text-decoration: none;
}

.footer__footer--link:first-of-type {
  padding-left: 0;
}

.copyright {
  color: #bcbcbd;
  padding-left: 1rem;
}


/* WHATS NEW
---------------------------------------------------------------------------- */



.whats-new--title {
  border-bottom: rgba(0,0,0,0.2) solid 1px;
  margin-bottom: 2.1rem;
  position: relative;
  text-transform: uppercase;
}

.whats-new--container {
  margin-bottom: 8.9rem;
}

.whats-new--see-all {
  bottom: 2.1rem;
  color: var(--blue);
  font-weight: bold;
  position: absolute;
  right: 0;
  text-decoration: none;
}

.whats-new-item-container {
  display: flex;
}

.whats-new-item {
  display: inline-block;
  flex: 1;
  padding-right: 2rem;
}

.whats-new-item--date {
  display: block;
  font-family: var(--font-family--alt);
  margin: 1rem 0;
}

.whats-new-item--link {
  color: var(--blue);
  text-decoration: none;
}


/* CARDS
---------------------------------------------------------------------------- */

.card {
  background: var(--grey);
  border-radius: 0.7rem;
  color: white;
  margin-bottom: 2.8rem;
  min-height: 187px;
  padding: 3.5rem 2.1rem 2.1rem;
  position: relative;
}

.card__title {
  font-size: 2.1rem;
  line-height: 2.8rem;
  margin-top: 1rem;
}

.card__title:after {
  content: '\203A';
  font-size: 4.2rem;
  position: absolute;
  right: 2rem;
  top: 1.4rem;
}

.card__title--alt {
  font-size: 2.1rem;
}

.ct--img {
  align-items: center;
  display: flex;
  justify-content: flex-start;
}

.ct--img--arrow {
  font-size: 4.2rem;
  margin-left: auto;
}

.ct--img img {
  margin-right: 1.4rem;
}

.card__content {
  color: rgba(255, 255, 255, 0.8);
  margin: 1.5rem 0;
}

.card__list {
  color: white;
  display: relative;
  font-weight: bold;
  text-transform: uppercase;
}

.card__list li {
  border-top: rgba(255,255,255,0.2) solid 1px;
  margin: 0;
  padding: 1rem 0;
}

.card__list li:after {
  color: rgba(255,255,255,0.4);
  content: '\203A';
  font-size: 2.8rem;
  position: absolute;
  right: 0;
  top: 0.7rem;
}

.card__list--last {
  border-bottom: rgba(255,255,255,0.2) solid 1px;
  border-top: rgba(255,255,255,0.2) solid 1px;
}

.card--active {
  background-color: var(--red--dark);
}

.card--active .card__content {
  color: white;
}


/* IMAGE ROW
---------------------------------------------------------------------------- */
.image-row {
  border-radius: 0.7rem;
  display: flex;
  margin: 2.7rem 0 2.9rem;
  overflow: hidden;
  padding: 0;
}


.image-row-title {
  align-items: flex-end;
  display: flex;
  flex-flow: row wrap;
  flex-grow: 0;
  flex-shrink: 0;
  justify-content: flex-start;
}

.image-row-title--main {
  font-size: 2.8rem;
  margin: 0;
}

.image-row-title--main:after {
  color: rgba(0,0,0,0.2);
  content: '/';
  padding: 0 1rem;
}

.image-row-title--secondary {
  color: var(--blue);
  font-size: 2.1rem;
  margin-right: 2rem;
}

.image-row--icon {
  background-color: var(--red);
  border-radius: 40px;
  color: white;
  margin: 0 0.35rem;
  padding: 0.7rem 1.4rem;
}

.image-row img {
    margin: 0;
    max-width: 314px;
    padding: 0;
}

.image-row-center {
  align-items: center;
  background-position:center top;
  background: linear-gradient( rgba(112, 111, 115, 0.8), rgba(112, 111, 115, 0.8) ), url('/img/img-row-2.jpg');
  color: white;
  display: flex;
  justify-content: center;
  min-height: 20rem;
  min-width: 32rem;
  position: relative;
}

.image-row-center--description {
  text-align: center;
}

.image-row-center--social {
  bottom: 0;
  display: flex;
  justify-content: space-between;
  padding: 1rem;
  position: absolute;
  width: 100%;
}

.image-row-center--likes {
  margin-right: auto;
}

.experience-row {
  border-radius: 0.7rem;
  display: flex;
  font-size: 2.1rem;
  margin: 2.8rem 0 0;
  overflow: hidden;
  padding: 0;
}

.experience-row--h1 {
  display: block;
  margin: 0;
  text-align: center;
  width: 100%;
}

.full-width-exp-img {
  background-position: center;
  background: linear-gradient( rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.8) ), url('/img/experience__bg-grey.jpg');
  width: 100%;
}

.image-row-alt {
  align-items: center;
  background-position:center top;
  color: white;
  display: flex;
  justify-content: center;
  min-height: 20rem;
  min-width: 32rem;
  position: relative;
}

.ira--item1 {
  background: url('/img/shop.png');
}
.ira--item2 {
  background: url('/img/dine.png');
}
.ira--item3 {
  background: url('/img/enjoy.png');
}

/* FLEX TABLE
---------------------------------------------------------------------------- */

.table-wrapper {
  border-radius: 0.7rem;
  margin-top: 1.5rem;
  overflow: hidden;
}

.table-row {
  border-bottom: rgba(0, 0, 0, 0.2) solid 1px;
  display: flex;
  flex-flow: row nowrap;
  justify-content: space-around;
  width: 100%;
}

.table-header {
  background-color: var(--red--dark);
  border-bottom: 0px;
  color: white;
  flex: 1;
  font-weight: bold;
  justify-content: flex-end;
  margin-bottom: 1rem;
}

.table-header-item {
  align-items: center;
  display: flex;
  padding: 2rem 2rem 1.9rem;
}

.table-header-item img {
  padding-right: 0.7rem;
}

.th--active {
  background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2));
  position: relative;
}

.th--active:after {
  border-bottom: 1rem solid white;
  border-left: 1rem solid transparent;
  border-right: 1rem solid transparent;
  bottom: 0;
  content: '';
  height: 0;
  left: 40%;
  left: calc(50% - 2rem);
  position: absolute;
  width: 0;
}

.item__t1 {
  font-size: 2.1rem;
  margin-right: auto;
}

.item__t3 {
    margin-right: 1.5rem;
}

.item__t2, .item__t3 {
    margin: 0 0.5rem;
    text-transform: uppercase;
}

.table-title-row {
  font-weight: bold;
}

.item {
  align-items: center;
  display: flex;
  flex: 1;
  line-height: 2.4rem;
  margin: 0.9rem 1rem 0.9rem;
  width: auto;
}

  .item__1 {
     justify-content: flex-start;
  }
  .item__2 {
    flex: 2;
    height: 32px;
    justify-content: flex-start;
  }
  .item__3 {
    justify-content: flex-start;
  }
  .item__4 {
    justify-content: flex-start;
  }
  .item__5 {
    justify-content: center;
  }
  .item__6 {
  justify-content: flex-end;
  }


.table-bottom-link {
  color: var(--blue);
  font-weight: bold;
  min-width: 100%;
  text-align: center;
  text-decoration: none;
  text-transform: uppercase;
}

.table-disclaimer {
    font-style: italic;
    margin: 0 5.6% 2rem;
    text-align: center;
    width: 88.8%;
}

.table-disclaimer-home {
    font-style: italic;
    margin: 0 5.6% 0.5rem;
    text-align: center;
    width: 88.8%;
}

@media screen and (max-width: 600px) {

    .table-row {
      display: flex;
      flex-flow: row wrap;
      justify-content: flex-start;
      justify-content: space-between;
      width: 100%;
    }

    .item__t1,
    .table-title-row {
      display: none;
    }

    .item__t2,
    .item__t3 {
      margin: 0;
    }

    .table-item {
      flex-grow: 1;
      flex-shrink: 0;
      justify-content: flex-start;
      white-space: nowrap;
    }

    .item {
      justify-content: flex-start;
      margin: 0.9rem 0;
    }

    .item__2,
    .item__4 {
      flex: 1 50%;

    }

    .item__1,
    .item__6 {
      flex: 1 20%;
    }
    .item__3,
    .item__5 {
      flex: 1 30%;
    }

    .item__5:before {
      content:'Terminal';
      margin-right:0.7rem;
    }
    .item__5--title:before {
      content:'';
    }
    .item__6 {
      font-weight: bold;
      justify-content: flex-start;
    }

}

@media screen and (max-width: 400px) {
  .item__1 {
    order: 3;
  }
  .item__2 {
    order: 4;
  }
  .item__3 {
    order: 2;
  }
  .item__4 {
    order: 1;
  }
  .item__5 {
    order: 5;
  }
  .item__6 {
    order: 6;
  }
}






.full-width-bg-img {
  background-position: center;
  background-size: cover;
  background: linear-gradient( rgba(255, 255, 255, 0.6), rgba(255, 255, 255, 0.6) ), url('/img/section__bg.jpg');
  width: 100%;
}

.tnf-wrapper {
  align-items: center;
  border-radius: 0.7rem;
  color: white;
  display: flex;
  flex-flow: column nowrap;
  justify-content: flex-start;
  overflow: hidden;
}

.tnf-title {
  display: flex;
  flex: 1;
  justify-content: flex-start;
  text-transform: uppercase;
  width: 100%;
}

.tnf-title span {
    margin: 2.1rem;
}

.tnf-title-main,
.tnf-col-lg--main {
  font-family:var(--font-family--alt);
  font-size: 2.8rem;
  font-weight: bold;
  line-height: 2.8rem;
}

.tnf-body {
  display: flex;
  flex-flow: row nowrap;
  flex: 1;
  width: 100%;
}

.tnf-body--title {
  border-bottom: solid 1px rgba(255,255,255,0.2);
  font-size: 2.1rem;
  line-height: 2.1rem;
  margin: 2.1rem;
  padding-bottom: 1.4rem;
}

.tnf-body--item {
  margin: 0.5rem 2.1rem;
  text-transform: uppercase;
}

.tnf-body--item:last-child {
  margin-bottom: 3rem;
}

.tnf-col {
  display: flex;
  flex-flow: column wrap;
  flex: 1;
}

.tnf-col span {
  align-items: center;
  display: flex;
}

.tnf-col img {
  padding-right: 1.4rem;
}

.tnf-col-lg {
  align-items: center;
  background-image: linear-gradient(to right, rgba(87, 86, 91, 1) 33.33%, rgba(112, 111, 115, 1) 66.66%,  rgba(135, 134, 137, 1));
  display: flex;
  flex: 3;
  justify-content: space-between;
}

.tnf-col-lg--main,
.tnf-col-lg--sub {

}

.tnf-colorbg {
  background-color: rgba(235, 65, 72, 1);
  color: white;
}


.tnf--item2 {background-color: rgba(87, 86, 91, 1);}
.tnf--item3 {background-color: rgba(112, 111, 115, 1);}
.tnf--item4 {background-color: rgba(135, 134, 137, 1);}


.flight-today,
.flight-date {
  font-size: 1.8rem;
  margin-right: 0.7rem;
}

.flight-today {
  font-style: italic;
  margin-left: 2.8rem;
}

.detail__item {
  align-items: flex-start;
  border-right: rgba(112, 111, 115, 0.2) solid 1px;
  display: flex;
  flex-flow: column;
  justify-content: center;
  padding: 0.7rem 4.8rem;
}

.detail__item:first-of-type {
  padding: 0.7rem 4.8rem 0.7rem 0;
}

.detail__item:last-child {
  border-right: 0px;
}

.detail__item--main {
  color: var(--grey);
  font-family: var(--font-family--alt);
  font-size: 2.8rem;
  font-weight: bold;
  margin-bottom: 2.1rem;
}

.detail__item--main--icon {
  margin: 0 2.1rem;
}

.detail__item--main--img {
  height: 28px;
}

.large-date {
  font-size: 1.8rem;
  margin-left: 1.4rem;
}


.header__mobile {
  display: none;
}

.mobile-search {
  display: none;
}

.banner__slider--controls-m {
  display: none;
}

.responsive-only {
  display: none;
}

@media screen and (max-width: 767px) {

  ul {
    padding: 0;
  }

  li {
    padding: 0;
  }

  h1,
  .h1 {
    margin: 1.4rem 0;
  }

  .responsive-only {
    display: block;
  }

  .desktop-only {
    display: none;
  }

  .inner--main {
    padding: 3.5rem 0;
  }

  .inner--short {
    padding: 2.1rem 0 0;
  }

  .inner--header {
    padding: 1rem 0 2.1rem;
  }

  .flex-column-mobile {
    flex-flow: column wrap;
  }

  .col-1 {
    margin: 0;
    padding: 0;
    flex: 1 0 25%;
  }

  .col-2 {
    flex: 1 0 50%;
    min-width: 280px;
    border-top: 1px solid rgba(255,255,255,0.2);
    padding-top: 2.1rem;
  }

  .table-disclaimer-home {
    margin: 0;
    padding: 0;
    width: 100%;
  }

  .banner,
  .banner--home {
    max-height: 16rem;
  }

  .secondary-nav {
    position: relative;
    transform: translateY(0%);
  }

  .secondary-nav .inner--secondary {
    padding: 0;
  }

  .nav__secondary {
    display: flex;
    flex-flow: column wrap;
    padding: 1rem;
  }

  .nav__secondary .white-up-triangle-active:after {
    display: none;
  }

  .nav__secondary--link {
    line-height: 51px;
    padding: 0;
  }

  .nav__secondary--link:not(:first-child) {
      border-left: 0px;
  }

  .nav__secondary--link:not(:last-child) {
      border-bottom: 1px solid rgba(255,255,255,0.2);
  }

  .banner__background {
    height: 16rem;
  }

  .banner__row {
    align-items: baseline;
    flex-flow: column nowrap;
  }

  .banner__left {
    border-bottom: rgba(255, 255, 255, 0.6) solid 1px;
    padding-bottom: 1rem;
    width: 100%;
  }

  .banner__right {
    margin: 1.4rem 0;
  }

  .banner__slider,
  .banner__slider--controls {
    display: none;
  }

  .banner__slider__mobile-bg {
    border-radius: 0.7rem;
    display: flex;
    margin: 0;
    overflow: hidden;
    padding: 0;
  }

  .banner__slider--controls-m {
    display: flex;
    justify-content: center;
    width: 100%;
  }

  .inner {

    padding-left: 1rem;
    padding-right: 1rem;
  }

  .header--language {
    padding: 0.3rem 0;
  }

  .header__logo {
    height: 44px;
    width: 149px;
  }

  .button {
    padding: 1.6rem 1.6rem;
  }

  .search-span-desktop {
    display: none;
  }

  .grey-bg--responsive-only {
    background-color: var(--grey--light);
  }

  .whats-new--container {
    margin-bottom: 2.1rem;
  }

  .whats-new--title {
    border: 0px;
    margin-bottom: 0;
  }

  .whats-new-item {
    display: none;
  }
 .whats-new-item--active {
   display: flex;
   flex-flow: column;
 }

.inner--bottom {
  padding: 2.1rem 1rem 0;
}

.footer__social {
  padding: 3.5rem 0;
}

.subscribe-form__input {
    width: calc(100% - 2.1rem);
}

.footer__social--inner {
  flex-flow: column wrap;
}

.footer__share {
  order: 2;
  margin-top: 2.1rem;
  margin-bottom: 2.1rem;
}

.footer__main .inner {
  padding-top: 0;
  padding-bottom: 0;
}

.footer__navigation--left {
    padding: 0.7rem 0;
    position: relative;
}

.footer__navigation--left li {
  display: none;
}

.footer__navigation--left .footer-left-active {
  display: block;
  position: relative;
  width: 100%;
}

.footer-left-active:before {
  border-left: 0.5rem solid transparent;
  border-right: 0.5rem solid transparent;
  border-top: 0.5rem solid white;
  content: '';
  display: block;
  position: absolute;
  left: 95%;
  left: calc(100% - 1rem);
  top: 0.7rem;
}

.footer__navigation--left:after {
  border-top: 1rem solid rgba(0,0,0,0.2);
  border-left: 1rem solid transparent;
  border-right: 1rem solid transparent;
  content: '';
  position: absolute;
  bottom: -1rem;
  left: 48%;
  left: calc(50% - 1rem);
}




.footer__navigation--right {
  background-color: rgba(255,255,255,0.2);
  flex-flow: row wrap;
  margin: 0 -1rem;
  padding: 1rem 1rem 0.7rem;
}

.footer__navigation--right .col-1 li {
  display: none;
}

.footer__navigation--right .col-1 .flat-list--first {
  display: block;
  font-weight: normal;
}

.footer__navigation--right:after {
  display: none;
}

.footer__contact {
  padding-left: 0;
}

.row-footer {
  flex-flow: column;
}

.footer__footer .row--reverse {
  justify-content: center;
}






  .header__nav {
    background-color: var(--blue);
    display: none;
    left: 0;
    margin: 0;
    min-width: 100%;
    padding: 0;
    position: fixed;
    top: 0;
    z-index: 9999;
  }

  .header__nav--link {
    border-bottom: rgba(255,255,255,0.2) solid 1px;
    color: white;
    display: block;
    margin: 0;
    padding: 1rem 0.5rem;
  }

  .header__nav--link.search {
    display: none;
  }

  .mobile-search {
    display: block;
    max-width: 100vw;
  }

}
```

**Comment by ibrokemycomputer** [comment]
I apologize if there is a better way to do it, I am just getting used to the git flow :/

**Comment by cogux** [comment]
I have a similar problem with arch linux

**Comment by SeanJM** [comment]
The issue is the CSS variables. They are not supported *yet*. It’ll be the next thing I add.

**Comment by ibrokemycomputer** [comment]
Sounds good, I'll give you your star back since it works great on other code I have used.

**Comment by maxsteenbergen** [comment]
The following line consistently triggers the same error. I manually converted each CSS block in a separate file until I reached the error, and removing this line solved the error.

`background-image: linear-gradient(33deg, hsl(200,80%,40%), hsl(155,75%,45%));`

**Comment by HannesDev** [comment]
_gradient_ seems to be the cause of the error.

My line that reproduces the error:
```
progress::-webkit-progress-value {
  background       : linear-gradient(
                       left,
                       lighten($c__secondary, 10%),
                       darken($c__secondary, 10%)
                     );
}
```

**Comment by SeanJM** [comment]
Try to keep your issues in separate threads. I'm going to move this issue to https://github.com/SeanJM/css-clean/issues/4
