### ISSUE TITLE
Uncaught TypeError: settings.getTab is not a function

### ISSUE THREAD

**Issue by johnosullivan** [SeanJM/atom-css-clean#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-css-clean](https://github.com/SeanJM/atom-css-clean) package 2.19.6

### Stack Trace

Uncaught TypeError: settings.getTab is not a function

```
At /Users/johnosullivan/.atom/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/commentBlock.js:111

TypeError: settings.getTab is not a function
    at formatSpecialComment (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/commentBlock.js:111:24)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/commentBlock.js:153:12)
    at /packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:26:30
    at Array.map (native)
    at mapValue (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/modules/mapValue.js:25:17)
    at getValue (/packages/atom-css-clean/node_modules/css-clean/src/main/getValue/getValue.js:4:10)
    at cleanCss (/packages/atom-css-clean/node_modules/css-clean/index.js:19:10)
    at module.exports (/packages/atom-css-clean/node_modules/css-clean/index.js:23:10)
    at /packages/atom-css-clean/main.js:43:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:26.8.0 css-clean:convert (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:22.8.0 core:select-all (input.hidden-input)
     -0:19.6.0 css-clean:convert (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.18 
atom-css-clean 2.19.6 
atom-typescript 11.0.1 
busy-signal 1.3.0 
intentions 1.1.2 
linter 2.1.2 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
```

**Comment by stianmandarin** [comment]
Identical problem here (except I have fewer non core packages)

**Comment by SeanJM** [comment]
I know what the issue is. The next time I have free time, I’ll fix it.

Sean

**Comment by stianmandarin** [comment]
Thank you Sean! This package is the main reason I use Atom. Again, thanks!

**Comment by SeanJM** [comment]
Me too. :)

**Comment by SeanJM** [comment]
Fixed
